### ISSUE TITLE
Regexp with `#$` breaks Racc parser

### ISSUE THREAD

**Issue by rafaelfranca** [seattlerb/debride#10]
Seems that the combination of `#` and `$` on this exactly order (`#$`) makes racc to fail.

A simple example of a file that reproduces this error:

```ruby
class Foo
  validates :password, format: { with: /[#$]/ }
end
```

The output:

```
/opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/racc/parser.rb:529:in `on_error': foo.rb:2 :: parse error on value ":" (tCOLON) (Racc::ParseError)
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1124:in `on_error'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/racc/parser.rb:258:in `do_parse'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1036:in `block in process'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1024:in `process'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1357:in `block in process'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1355:in `each'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1355:in `process'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/lib/debride.rb:89:in `process_rb'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/lib/debride.rb:80:in `block in run'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/lib/debride.rb:67:in `each'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/lib/debride.rb:67:in `run'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/lib/debride.rb:62:in `run'
	from /opt/boxen/rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/debride-1.2.0/bin/debride:5:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p247/bin/debride:23:in `load'
	from /opt/boxen/rbenv/versions/2.0.0-p247/bin/debride:23:in `<main>'
```

And it seems to be valid Ruby:

```irb
>> r = /[#$]/
=> /[#$]/
>> r
=> /[#$]/
>> r =~ '$'
=> 0
>> r =~ 'a'
=> nil
>> r =~ '#'
=> 0
>> r =~ '$'
=> 0
```

**Comment by zenspider** [comment]
Yup. Known issue fixed in next version of ruby_parser. 

I hope that regex isn't for detecting comment lines.

**Comment by rafaelfranca** [comment]
Cool! So closing this. I'm glad it is already fixed.

@zenspider you would be surprised if I told you what this regex does.
