### ISSUE TITLE
Should rescue RegexpError while parsing file.

### ISSUE THREAD

**Issue by mrdShinse** [seattlerb/debride#34]
Because `ruby_parser` may throw `RegexpError`. - [`here is source`](https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby_parser_extras.rb#L771).

If parsing file contains non escaped non ASCII char, debride fail while parsing file.
debride's parsing log when failing is below.

I think we should skip parsing these file and finish `Debride#run` script. isn't is?

```
$ rake run D="./throw_regexperror_sample.rb"
WARNING: invalid multibyte character: /\【/ for "\\【" ""
WARNING: trying to recover with ENC_UTF8
WARNING: trying to recover with ENC_NONE
rake aborted!
RegexpError: /.../n has a non escaped non ASCII character in non ASCII-8BIT script: /\【/
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:110:in `process_rb'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:89:in `block in run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `each'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:71:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:39:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:43:in `block in <top (required)>'
RegexpError: invalid multibyte character: /\【/
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:110:in `process_rb'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:89:in `block in run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `each'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:71:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:39:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:43:in `block in <top (required)>'
RegexpError: invalid multibyte character: /\【/
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:110:in `process_rb'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:89:in `block in run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `each'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:76:in `run'
/Users/shinse/github/mrdshinse/debride/lib/debride.rb:71:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:39:in `run'
/Users/shinse/github/mrdshinse/debride/Rakefile:43:in `block in <top (required)>'
Tasks: TOP => run
(See full trace by running task with --trace)
```

**Comment by zenspider** [comment]
Done. thanks!
