### ISSUE TITLE
Debride failing with latest version of sexp_processor

### ISSUE THREAD

**Issue by jcavalieri** [seattlerb/debride#41]
The gem sexp_processor updated today:
https://rubygems.org/gems/sexp_processor/versions/4.14.0

And now calling debride fails with this.

Workaround is to install the previous version of sexp_processor. E.g. `gem install sexp_processor -v 4.13.0`

```
/usr/local/bundle/gems/sexp_processor-4.14.0/lib/sexp_matcher.rb:160:in `<class:Sexp>': private method `alias_method' called for #<Class:Sexp> (NoMethodError)
	from /usr/local/bundle/gems/sexp_processor-4.14.0/lib/sexp_matcher.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/sexp_processor-4.14.0/lib/sexp.rb:380:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/ruby_parser-3.14.2/lib/ruby_parser_extras.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/ruby_parser-3.14.2/lib/ruby_parser.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/debride-1.8.2/lib/debride.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/debride-1.8.2/bin/debride:3:in `<top (required)>'
	from /usr/local/bundle/bin/debride:23:in `load'
	from /usr/local/bundle/bin/debride:23:in `<main>'
ERROR: Job failed: command terminated with exit code 1
```

**Comment by zenspider** [comment]
Thanks for reporting! This has already been fixed with sexp_processor 4.14.0.

Also, I highly recommend you get off of ruby 2.4. The EOL for it is this March and there are a lot of advancements available in ruby 2.5+.
